-- PDF → Markdown 변환 대기열. document_id는 변환 결과를 담을 placeholder Markdown 문서,
-- source_document_id는 변환할 PDF 원본 문서다. worker가 created_at 순서(pending)대로 처리한다.
CREATE TABLE document_convert_queue (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    document_id        varchar(255)             NOT NULL,
    source_document_id varchar(255)             NOT NULL,
    status             varchar(255)             NOT NULL,
    created_at         timestamp with time zone NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_document_convert_queue_document UNIQUE (document_id),
    CONSTRAINT fk_document_convert_queue_document
        FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE,
    CONSTRAINT fk_document_convert_queue_source_document
        FOREIGN KEY (source_document_id) REFERENCES documents(id) ON DELETE CASCADE
);
