-- Flyway baseline 스키마 (V1)
--
-- 생성 방법: 로컬 DB를 비운 뒤 ddl-auto=update로 엔티티 16개 기준 깨끗한 스키마를
-- 재생성하고 pg_dump --schema-only 로 추출했다. psql 전용 메타명령(\restrict 등)과
-- SET 헤더만 제거했고 DDL은 그대로 보존한다.
-- 관리 제외: flyway_schema_history(Flyway 자체), spring_session*(Spring Session JDBC가 별도 관리).
--
-- 주의: 이미 머지된 이 파일은 절대 수정하지 않는다. 스키마 변경은 새 Vn__*.sql로 추가한다.

CREATE TABLE public.chat_message_references (
    id bigint NOT NULL,
    document_id character varying(255),
    quote text,
    rank integer,
    reference_type character varying(255) NOT NULL,
    source_block_ids text,
    chat_message_id character varying(255) NOT NULL
);

ALTER TABLE public.chat_message_references ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_references_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.chat_message_related_pages (
    id bigint NOT NULL,
    depth integer,
    page_type character varying(255),
    rank integer,
    relevance_score double precision,
    role character varying(255),
    slug character varying(255),
    title character varying(255),
    wiki_page_id character varying(255),
    chat_message_id character varying(255) NOT NULL
);

ALTER TABLE public.chat_message_related_pages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_related_pages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.chat_messages (
    id character varying(255) NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    error_message character varying(255),
    pair_id character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    wiki_page_id character varying(255),
    session_id character varying(255) NOT NULL
);

CREATE TABLE public.chat_partial_wiki (
    id character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    document_id character varying(255) NOT NULL,
    pair_id character varying(255) NOT NULL,
    session_id character varying(255) NOT NULL,
    wiki_page_id character varying(255) NOT NULL
);

CREATE TABLE public.chat_sessions (
    id character varying(255) NOT NULL,
    context_summary text,
    context_summary_updated_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    last_message_at timestamp(6) with time zone,
    title character varying(255),
    user_id character varying(255) NOT NULL,
    wiki_export_document_id character varying(255),
    wiki_page_id character varying(255),
    workspace_id character varying(255) NOT NULL
);

CREATE TABLE public.document_processing_queue (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    document_id character varying(255) NOT NULL,
    status character varying(255) NOT NULL
);

ALTER TABLE public.document_processing_queue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_processing_queue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.document_wiki_links (
    document_id character varying(255) NOT NULL,
    relation_type character varying(255) NOT NULL,
    wiki_page_id character varying(255) NOT NULL,
    confidence double precision,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT document_wiki_links_relation_type_check CHECK (((relation_type)::text = ANY ((ARRAY['source_of'::character varying, 'extracted_concept'::character varying])::text[])))
);

CREATE TABLE public.documents (
    id character varying(255) NOT NULL,
    byte_size bigint NOT NULL,
    content_hash character varying(255) NOT NULL,
    error_message text,
    extracted_text_uri character varying(255),
    filename character varying(255) NOT NULL,
    mime_type character varying(255) NOT NULL,
    origin character varying(255),
    pipeline_input_markdown text,
    pipeline_run_id character varying(255),
    processed_at timestamp(6) with time zone,
    processing_stage character varying(255),
    processing_started_at timestamp(6) with time zone,
    processing_updated_at timestamp(6) with time zone,
    reconciled_at timestamp(6) with time zone,
    selection_mode character varying(255),
    source_uri character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    uploaded_at timestamp(6) with time zone NOT NULL,
    user_id character varying(255) NOT NULL,
    workspace_id character varying(255) NOT NULL,
    CONSTRAINT documents_status_check CHECK (((status)::text = ANY ((ARRAY['uploaded'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying])::text[])))
);

CREATE TABLE public.source_blocks (
    block_id character varying(255) NOT NULL,
    document_id character varying(255) NOT NULL,
    text text NOT NULL
);

CREATE TABLE public.user_oauth_accounts (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    provider character varying(255) NOT NULL,
    provider_user_id character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL
);

ALTER TABLE public.user_oauth_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_oauth_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    revoked_at timestamp(6) with time zone,
    token_hash character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL
);

ALTER TABLE public.user_refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    display_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255),
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.wiki_page_links (
    from_page_id character varying(255) NOT NULL,
    link_type character varying(255) NOT NULL,
    to_page_id character varying(255) NOT NULL,
    confidence double precision,
    created_at timestamp(6) with time zone NOT NULL,
    label character varying(255),
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.wiki_pages (
    id character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    markdown_uri character varying(255),
    page_type character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    summary text,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id character varying(255) NOT NULL,
    workspace_id character varying(255) NOT NULL,
    CONSTRAINT wiki_pages_page_type_check CHECK (((page_type)::text = ANY ((ARRAY['source'::character varying, 'concept'::character varying])::text[]))),
    CONSTRAINT wiki_pages_status_check CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'active'::character varying, 'failed'::character varying])::text[])))
);

CREATE TABLE public.workspace_members (
    joined_at timestamp(6) with time zone NOT NULL,
    role character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL,
    workspace_id character varying(255) NOT NULL
);

CREATE TABLE public.workspaces (
    id character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    name character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

ALTER TABLE ONLY public.chat_message_references
    ADD CONSTRAINT chat_message_references_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_message_related_pages
    ADD CONSTRAINT chat_message_related_pages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_partial_wiki
    ADD CONSTRAINT chat_partial_wiki_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_sessions
    ADD CONSTRAINT chat_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.document_processing_queue
    ADD CONSTRAINT document_processing_queue_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.document_wiki_links
    ADD CONSTRAINT document_wiki_links_pkey PRIMARY KEY (document_id, relation_type, wiki_page_id);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.source_blocks
    ADD CONSTRAINT source_blocks_pkey PRIMARY KEY (block_id, document_id);

ALTER TABLE ONLY public.document_processing_queue
    ADD CONSTRAINT uk2cgpdw6i4thj99hco43pt5nna UNIQUE (document_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT ukeafca5s6k4behm6am8avmcik3 UNIQUE (content_hash);

ALTER TABLE ONLY public.chat_partial_wiki
    ADD CONSTRAINT uki4f96q32bs1t54m17mlji56o1 UNIQUE (pair_id, wiki_page_id);

ALTER TABLE ONLY public.user_oauth_accounts
    ADD CONSTRAINT uq_user_oauth_accounts_provider_provider_user_id UNIQUE (provider, provider_user_id);

ALTER TABLE ONLY public.wiki_pages
    ADD CONSTRAINT uq_wiki_pages_workspace_type_slug UNIQUE (user_id, workspace_id, page_type, slug);

ALTER TABLE ONLY public.user_oauth_accounts
    ADD CONSTRAINT user_oauth_accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_refresh_tokens
    ADD CONSTRAINT user_refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.wiki_page_links
    ADD CONSTRAINT wiki_page_links_pkey PRIMARY KEY (from_page_id, link_type, to_page_id);

ALTER TABLE ONLY public.wiki_pages
    ADD CONSTRAINT wiki_pages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workspace_members
    ADD CONSTRAINT workspace_members_pkey PRIMARY KEY (user_id, workspace_id);

ALTER TABLE ONLY public.workspaces
    ADD CONSTRAINT workspaces_pkey PRIMARY KEY (id);

CREATE INDEX idx_documents_reconcile ON public.documents USING btree (origin, status, reconciled_at);

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fk3cpkdtwdxndrjhrx3gt9q5ux9 FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.workspace_members
    ADD CONSTRAINT fk6vtnpc3eexk504u61uepn40p1 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.chat_message_related_pages
    ADD CONSTRAINT fkfvsxebu3rxb57mwu3ly84hmg9 FOREIGN KEY (chat_message_id) REFERENCES public.chat_messages(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.chat_message_references
    ADD CONSTRAINT fkn19klvttpilio6ma00h013gwm FOREIGN KEY (chat_message_id) REFERENCES public.chat_messages(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.workspace_members
    ADD CONSTRAINT fkw9hq87n3rvq2c4j47qo78i5r FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;
