apiVersion: v1
kind: ServiceAccount
metadata:
  name: fruition-access
  namespace: fruition
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fruition-document
  namespace: fruition
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_ME_DOCUMENT_STORAGE_ROLE_ARN
    eks.amazonaws.com/sts-regional-endpoints: 'true'
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fruition-pipeline
  namespace: fruition
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_ME_PIPELINE_STORAGE_ROLE_ARN
    eks.amazonaws.com/sts-regional-endpoints: 'true'
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fruition-converter
  namespace: fruition
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fruition-access-migration
  namespace: fruition
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fruition-document-migration
  namespace: fruition
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fruition-ai-migration
  namespace: fruition
automountServiceAccountToken: false
