-- AI 작업 로그. 사용자에게 보여줄 AI 작업(문서 AI 편집, Wiki ingest·lint, 복구) 이력을 한곳에 모은다.
-- CloudWatch application log나 LLM 호출 trace와는 성격이 다른 업무 데이터다.
CREATE TABLE ai_operation_logs (
    operation_id           varchar(255)             NOT NULL,
    workspace_id           varchar(255)             NOT NULL,
    user_id                varchar(255)             NOT NULL,
    -- document_edit | ingest | lint | restore
    operation_type         varchar(20)              NOT NULL,
    -- 어느 원문 문서의 작업인지. 복구 대상 선정의 근거이며 lint는 NULL이다.
    target_document_id     varchar(255),
    -- processing | applying | notify_pending | rebuilding
    -- succeeded | partially_succeeded | failed | conflict
    status                 varchar(20)              NOT NULL,
    summary                text,
    changed_resource_count integer                  NOT NULL DEFAULT 0,
    -- 복구 작업이 되돌린 대상 작업
    restored_from          varchar(255),
    -- 복구 시 llmPipeline에 보낸 조립 지시서 원본. 재조립 결과 수신과 재전송에 사용한다.
    restore_manifest       jsonb,
    -- 완료 콜백 payload의 정규화 해시. 같은 payload 재전송은 200, 다른 payload는 409로 가른다.
    payload_hash           varchar(64),
    created_at             timestamp with time zone NOT NULL,
    completed_at           timestamp with time zone,
    PRIMARY KEY (operation_id),
    CONSTRAINT fk_ai_operation_logs_workspace
        FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_operation_logs_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ai_operation_logs_target_document
        FOREIGN KEY (target_document_id) REFERENCES documents(id) ON DELETE SET NULL,
    CONSTRAINT fk_ai_operation_logs_restored_from
        FOREIGN KEY (restored_from) REFERENCES ai_operation_logs(operation_id)
);

-- 목록 조회: 워크스페이스 + 유형 + 최신순
CREATE INDEX idx_ai_operation_logs_workspace_type
    ON ai_operation_logs(workspace_id, operation_type, created_at DESC);

-- 복구 대상 선정: 특정 문서의 작업을 시간순으로
CREATE INDEX idx_ai_operation_logs_target_document
    ON ai_operation_logs(target_document_id, created_at);

-- 작업 1회가 바꾼 리소스를 1행씩 기록한다. 일어난 일의 감사 기록이며 나중에 고치지 않는다.
-- diff 본문은 저장하지 않는다. 전체 본문이 버전 테이블에 있어 조회 시 재계산할 수 있고,
-- 중복 저장하면 두 값이 어긋날 여지가 생긴다. 줄 수만 남긴다.
CREATE TABLE ai_operation_changes (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    operation_id    varchar(255) NOT NULL,
    -- document | wiki_page
    resource_type   varchar(20)  NOT NULL,
    -- resource_type에 따라 documents.id 또는 wiki_pages.id를 가리키는 다형 참조라 FK를 걸지 않는다.
    -- 대상이 삭제돼도 로그는 남아야 한다.
    resource_id     varchar(255) NOT NULL,
    -- 손대기 직전 버전. NULL이면 새로 만든 것이며 되돌릴 지점이 없다는 뜻이다.
    before_revision bigint,
    -- 이 작업이 만든 버전. 위임·실패면 NULL이다.
    after_revision  bigint,
    -- created | updated | deleted | restored | delegated | rebuilt | rebuild_failed
    change_type     varchar(20)  NOT NULL,
    change_summary  text,
    additions       integer,
    deletions       integer,
    PRIMARY KEY (id),
    CONSTRAINT fk_ai_operation_changes_operation
        FOREIGN KEY (operation_id) REFERENCES ai_operation_logs(operation_id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_operation_changes_operation
    ON ai_operation_changes(operation_id);

-- 페이지별 변경 이력 역조회
CREATE INDEX idx_ai_operation_changes_resource
    ON ai_operation_changes(resource_id, id);

-- 콜백 재전송 시 변경내역 중복을 막는 최종 방어선.
-- revision은 매번 새로 채번되므로 버전 테이블의 PK만으로는 재전송을 걸러낼 수 없다.
-- change_type을 키에 포함하는 이유는 한 복구 작업이 같은 페이지에 delegated와 rebuilt를 차례로 남기기 때문이다.
CREATE UNIQUE INDEX uk_ai_operation_changes_operation_resource_type
    ON ai_operation_changes(operation_id, resource_type, resource_id, change_type);

-- 이 버전을 만든 AI 작업. 사용자가 직접 편집한 버전이면 NULL이다.
ALTER TABLE document_content_versions
    ADD COLUMN operation_id varchar(255);

ALTER TABLE document_content_versions
    ADD CONSTRAINT fk_document_content_versions_operation
        FOREIGN KEY (operation_id) REFERENCES ai_operation_logs(operation_id) ON DELETE SET NULL;
