-- access-svc Flyway baseline (V1)
--
-- 생성 방법: MSA DB 분리(access_db) 시점의 로컬 DB(fruition_mvp)에서
-- access 소유 테이블 7개(users, user_oauth_accounts, user_refresh_tokens,
-- email_verifications, workspaces, workspace_members, idempotency_records)를
-- pg_dump --schema-only 로 추출했다. SET 헤더·OWNER 지정 등 잡음만 제거하고 DDL은 그대로 보존한다.
-- 관리 제외: flyway_schema_history(Flyway 자체), spring_session*(Spring Session JDBC가 별도 관리).
--
-- 주의: 이미 머지된 이 파일은 절대 수정하지 않는다. 스키마 변경은 새 Vn__*.sql로 추가한다.

CREATE TABLE public.users (
    id character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    display_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255),
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE public.user_oauth_accounts (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    provider character varying(255) NOT NULL,
    provider_user_id character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL
);

ALTER TABLE public.user_oauth_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_oauth_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    revoked_at timestamp(6) with time zone,
    token_hash character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL
);

ALTER TABLE public.user_refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.email_verifications (
    id character varying(64) NOT NULL,
    email character varying(255) NOT NULL,
    purpose character varying(32) NOT NULL,
    code_hash character varying(128) NOT NULL,
    code_expires_at timestamp with time zone NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    confirmed_at timestamp with time zone,
    token_hash character varying(128),
    token_expires_at timestamp with time zone,
    consumed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.workspaces (
    id character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    name character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by character varying(255)
);

CREATE TABLE public.workspace_members (
    joined_at timestamp(6) with time zone NOT NULL,
    role character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL,
    workspace_id character varying(255) NOT NULL,
    CONSTRAINT workspace_members_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'MEMBER'::character varying])::text[])))
);

-- access 전용 idempotency 기록. core_db에도 같은 이름의 테이블이 있으며 각 서비스가 자기 DB의 것을 쓴다.
CREATE TABLE public.idempotency_records (
    id uuid NOT NULL,
    user_id character varying(255) NOT NULL,
    endpoint_scope character varying(255) NOT NULL,
    idempotency_key character varying(255) NOT NULL,
    request_hash character varying(64) NOT NULL,
    response_status integer NOT NULL,
    resource_id character varying(255),
    response_body jsonb,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.user_oauth_accounts
    ADD CONSTRAINT user_oauth_accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_oauth_accounts
    ADD CONSTRAINT uq_user_oauth_accounts_provider_provider_user_id UNIQUE (provider, provider_user_id);

ALTER TABLE ONLY public.user_refresh_tokens
    ADD CONSTRAINT user_refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.email_verifications
    ADD CONSTRAINT email_verifications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workspaces
    ADD CONSTRAINT workspaces_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workspace_members
    ADD CONSTRAINT workspace_members_pkey PRIMARY KEY (user_id, workspace_id);

ALTER TABLE ONLY public.idempotency_records
    ADD CONSTRAINT idempotency_records_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.idempotency_records
    ADD CONSTRAINT uq_idempotency_records_scope_key UNIQUE (user_id, endpoint_scope, idempotency_key);

CREATE INDEX idx_email_verifications_email_purpose_created ON public.email_verifications USING btree (email, purpose, created_at);

CREATE INDEX idx_email_verifications_token_hash ON public.email_verifications USING btree (token_hash);

CREATE INDEX idx_workspaces_deleted_at ON public.workspaces USING btree (deleted_at);

CREATE INDEX idx_idempotency_records_expires_at ON public.idempotency_records USING btree (expires_at);

-- users FK는 access_db 안에서 유지 가능하다 (전부 access 소유 테이블).
ALTER TABLE ONLY public.workspace_members
    ADD CONSTRAINT fk6vtnpc3eexk504u61uepn40p1 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.workspace_members
    ADD CONSTRAINT fkw9hq87n3rvq2c4j47qo78i5r FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.idempotency_records
    ADD CONSTRAINT fk_idempotency_records_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
